@maxhanna.Server_HostAddress = https://localhost:7299

GET {{maxhanna.Server_HostAddress}}/weatherforecast/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/weatherforecast/
Accept: application/json
###
PUT {{maxhanna.Server_HostAddress}}/weatherforecast/
Accept: application/json
###
GET {{maxhanna.Server_HostAddress}}/calendar/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/calendar/
Accept: application/json
###
DELETE {{maxhanna.Server_HostAddress}}/calendar/
Accept: application/json
###
GET {{maxhanna.Server_HostAddress}}/mining/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/mining/
Accept: application/json
###
PUT {{maxhanna.Server_HostAddress}}/mining/
Accept: application/json
###
GET {{maxhanna.Server_HostAddress}}/todo/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/todo/
Accept: application/json
###
DELETE {{maxhanna.Server_HostAddress}}/todo/
Accept: application/json
###
GET {{maxhanna.Server_HostAddress}}/file/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/file/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/file/
Accept: multipart/form-data
###
DELETE {{maxhanna.Server_HostAddress}}/file/
Accept: application/json
###
GET {{maxhanna.Server_HostAddress}}/notepad/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/notepad/
Accept: application/json
###
DELETE {{maxhanna.Server_HostAddress}}/notepad/
Accept: application/json
###
GET {{maxhanna.Server_HostAddress}}/contact/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/contact/
Accept: application/json
###
PUT {{maxhanna.Server_HostAddress}}/contact/
Accept: application/json
###
DELETE {{maxhanna.Server_HostAddress}}/contact/
Accept: application/json
###
GET {{maxhanna.Server_HostAddress}}/User/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/User/
Accept: application/json
###
PATCH {{maxhanna.Server_HostAddress}}/User/
Accept: application/json
###
DELETE {{maxhanna.Server_HostAddress}}/User/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/Chat/
Accept: application/json
### 
POST {{maxhanna.Server_HostAddress}}/News/
Accept: application/json
###
GET {{maxhanna.Server_HostAddress}}/Social/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/Social/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/Rom/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/Topic/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/Friend/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/Wordler/
Accept: application/json
###
GET {{maxhanna.Server_HostAddress}}/Wordler/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/Comment/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/CoinValue/
Accept: application/json
### 
POST {{maxhanna.Server_HostAddress}}/CurrencyValue/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/Reaction/
Accept: application/json
###
GET {{maxhanna.Server_HostAddress}}/Array/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/Array/
Accept: application/json
###
GET {{maxhanna.Server_HostAddress}}/Nexus/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/Nexus/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/Notification/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/Meta/
Accept: application/json
### 
POST {{maxhanna.Server_HostAddress}}/Ai/
Accept: application/json
### 
POST {{maxhanna.Server_HostAddress}}/Favourite/
Accept: application/json
### 
PUT {{maxhanna.Server_HostAddress}}/Favourite/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/Crawler/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/Trade/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/Top/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/Poll/
Accept: application/json
###
GET {{maxhanna.Server_HostAddress}}/Mastermind/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/Mastermind/
Accept: application/json
###
GET {{maxhanna.Server_HostAddress}}/Art/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/Art/
Accept: application/json
###