@maxhanna.Server_HostAddress = https://localhost:7299

GET {{maxhanna.Server_HostAddress}}/weatherforecast/
Accept: application/json
###
GET {{maxhanna.Server_HostAddress}}/calendar/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/calendar/
Accept: application/json
###
DELETE {{maxhanna.Server_HostAddress}}/calendar/
Accept: application/json
###
GET {{maxhanna.Server_HostAddress}}/mining/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/mining/
Accept: application/json
###
GET {{maxhanna.Server_HostAddress}}/todo/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/todo/
Accept: application/json
###
DELETE {{maxhanna.Server_HostAddress}}/todo/
Accept: application/json
###
GET {{maxhanna.Server_HostAddress}}/file/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/file/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/file/
Accept: multipart/form-data
###
DELETE {{maxhanna.Server_HostAddress}}/file/
Accept: application/json
###
GET {{maxhanna.Server_HostAddress}}/notepad/
Accept: application/json
###
POST {{maxhanna.Server_HostAddress}}/notepad/
Accept: application/json
###
DELETE {{maxhanna.Server_HostAddress}}/notepad/
Accept: application/json
###